const express = require("express")
const router = express.Router()
const PostController = require("../controller/PostController")
router.post("/addpost",PostController.addPost)
router.put("/:postId",PostController.updatePost)
router.delete("/:postId/:userId",PostController.deletePost)
router.put("/:postId/like",PostController.addLike)
router.put("/:postId/love",PostController.addLove)
router.get("/:postId",PostController.getPost)
router.get("/timeLine/:userId",PostController.getTimeLinePosts)
router.get("/posts/:userId",PostController.getProfilePosts)
router.post("/comment/:postId/:userId",PostController.addComment)
router.post("/comment/:postId",PostController.getUpdateComment)
module.exports = router