const express = require("express")
const router = express.Router()
const UserController = require("../controller/UserController")
const isAuth = require("../middleware/isAuth")
router.put("/:userId",UserController.updateUser)
router.put("/profile/:userId",UserController.updateprofile)
router.put("/cover/:userId",UserController.updateCover)
router.delete("/:userId",UserController.DeleteUser)
router.get("/:userId",UserController.getUser)
router.post("/:userId/follow",UserController.addFollow)
router.post("/:userId/unfollow",UserController.UnFollow)
router.post("/:userId/friend",UserController.AddFriend)
router.post("/:userId/friendrequest",UserController.FriendRequest)
router.post("/:userId/removefriendrequest",UserController.RemoveFriendRequest)
router.post("/:userId/unfriend",UserController.UnFriend)
router.get("/Users/all",UserController.getUsers)
router.post("/Users/all",UserController.getUserByName)
router.get("/users/:userId/friends",UserController.getProfileFriends)
router.get("/update/:userId",UserController.getUserUpdate)
router.post("/activeFriends",UserController.getActiveFriends)
router.post("/:userId/resetpassword",UserController.ChangePasswordEmail)
router.post("/:userId/changePassword",UserController.ChangePassword)
module.exports = router